### PR TITLE
16

### LINKED ISSUE #16: Feature: Increase maximum possible price
The system currently will reject any product being created with a price greater than $10,000. Increase that maximum to $17,500.

### PR DESCRIPTION
**Pull request by devinmgarcia**
Description of PR that completes issue here...

## Changes

- line 18 in models/product.py. changed MaxValueValidator from 10,000 to 17,500.

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

POST `/products` Creates a new product

```json
    {
        "id": 101,
        "name": "Kite",
        "price": 11000.0,
        "number_sold": 0,
        "description": "It flies high",
        "quantity": 60,
        "created_date": "2021-08-30",
        "location": "Pittsburgh",
        "image_path": null,
        "average_rating": null
    }
```

**Response**

HTTP/1.1 201 OK

```json
    {
        "id": 101,
        "name": "Kite",
        "price": 11000.0,
        "number_sold": 0,
        "description": "It flies high",
        "quantity": 60,
        "created_date": "2021-08-30",
        "location": "Pittsburgh",
        "image_path": null,
        "average_rating": null
    }
```

## Testing

Description of how to test code...

- [ ] Run Post to products with a price over 10k

## Related Issues

- Fixes #16

### CODE REVIEW

**Review by hannahhall — CHANGES_REQUESTED** [review]
Includes code from another pr. Either get that pr merged first or remove the changes from this pr. Make sure you're branching off main between tickets

**Comment by devinmgarcia** [comment]
Is this okay to merge now that 15 is complete?

**Comment by hannahhall** [comment]
The diff still has the other changes in it. Merge main into this branch, push up, then you should be good to merge

**Comment by devinmgarcia** [comment]
Alright, let me know if that works.

**Review by hannahhall — APPROVED** [review]
Approved!

**Pull request merged**
